FROM python:3.9

WORKDIR /app

COPY requirements.txt ./requirments.txt

RUN pip3 install streamlit 
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install pillow
RUN pip3 install sklearn
EXPOSE 8080

COPY . /app

CMD streamlit run --server.port 8080 --server.enableCORS false app.py


